package com.iotech.qualitrack.platform.ca.infrastructure.persistence.jpa.entities;

import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.ComplianceEventType;
import com.iotech.qualitrack.platform.shared.infrastructure.persistence.jpa.entities.AuditableAbstractPersistenceEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA persistence entity representing a compliance event table.
 *
 * <p>This entity stores audit trail entries generated by compliance-relevant
 * actions across bounded contexts.</p>
 */
@Entity
@Table(name = "compliance_events")
@Getter
@Setter
@NoArgsConstructor
public class ComplianceEventPersistenceEntity extends AuditableAbstractPersistenceEntity {

    @Column(name = "related_entity_id", nullable = false)
    private Long relatedEntityId;

    /**
     * Converted automatically by ComplianceEventTypePersistenceConverter.
     */
    @Column(name = "event_type", nullable = false, length = 100)
    private ComplianceEventType eventType;

    @Column(nullable = false, length = 1000)
    private String description;

    @Column(nullable = false, length = 30)
    private String timestamp;

    @Column(name = "resolved_by")
    private Long resolvedBy;
}