# Spring Application Name
spring.application.name=Qualitrack Platform

# Default profile
spring.profiles.default=dev

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.iotech.qualitrack.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.title=Qualitrack API
documentation.application.description=Qualitrack Platform REST API Documentation
documentation.application.version=1.0.0

# JWT Configuration Properties
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
