package com.iotech.qualitrack.platform.ra.infrastructure.documents;

import com.iotech.qualitrack.platform.ra.application.internal.outboundservices.InventoryReportData;

import java.io.IOException;
import java.time.Instant;
import java.util.List;

/** Inventory report contents using the same layout as the other reports (US97). */
final class InventoryReportPdfRenderer extends AbstractReportPdfRenderer {
    byte[] render(InventoryReportData data) {
        return renderDocument("Inventory report", data.laboratory() + " / Laboratory #" + data.laboratoryId(), () -> {
            metrics(List.of(new Metric("RAW MATERIALS", Integer.toString(data.materials()), TEAL),
                    new Metric("LOTS", Integer.toString(data.lots()), INK),
                    new Metric("BELOW MINIMUM", Long.toString(data.lowStock()), AMBER),
                    new Metric("EXPIRING", Long.toString(data.expiring()), RED)));
            section("01", "Business date and scope");
            paragraph(date(data.businessDate()) + " (America/Lima). Environments: " + data.environments().size() + ".", INK);
            paragraph("Usable stock counts released, unexpired lots with stock; physical stock counts every lot with stock. "
                    + "Expiration is evaluated on the business date.", MUTED);
            var number = 2;
            for (var environment : data.environments()) {
                section(String.format("%02d", number++), "Environment " + value(environment.code()) + " - " + value(environment.name()));
                if (environment.materials().isEmpty()) {
                    paragraph("No raw materials are kept in this environment.", MUTED);
                    continue;
                }
                table(List.of("Raw material", "Minimum", "Usable / physical", "Stock"),
                        environment.materials().stream().map(m -> List.of(value(m.code()) + "\n" + value(m.name()),
                                value(m.minimumStock()) + " " + value(m.unit()),
                                value(m.usableStock()) + " / " + value(m.physicalStock()) + " " + value(m.unit()),
                                human(m.stockStatus()))).toList(),
                        new float[]{.34f, .18f, .30f, .18f});
                var lots = environment.materials().stream().flatMap(m -> m.lots().stream().map(l -> List.of(
                        value(m.code()) + "\nLot #" + l.id() + " " + value(l.batchNumber()) + "\n" + value(l.supplier()),
                        value(l.availableAmount()) + " / " + value(l.initialAmount()) + " " + value(m.unit()),
                        date(l.receivedOn()) + "\n" + date(l.expiresOn()),
                        human(l.status()) + "\n" + human(l.expirationStatus()),
                        value(l.container())))).toList();
                if (lots.isEmpty()) paragraph("No lots received for these raw materials.", MUTED);
                else table(List.of("Lot", "Available / initial", "Received / expires", "Status / expiration", "Container"), lots,
                        new float[]{.30f, .18f, .18f, .17f, .17f});
            }
            if (data.environments().isEmpty()) paragraph("The laboratory has no environments.", MUTED);
            section(String.format("%02d", number), "Scope and authorship");
            paragraph("Quantities recorded at export; this report does not replace a physical count.", MUTED);
            provenance(data.generatedBy(), data.generatedAt());
        });
    }

    private void provenance(String user, Instant generatedAt) throws IOException {
        paragraph("Generated by " + value(user) + " on " + timestamp(generatedAt.toString()), MUTED);
    }
}
