package com.iotech.qualitrack.platform.laboratory.domain.model.entities;

import lombok.Getter;

/**
 * The LaboratoryAddress domain entity.
 *
 * <p>Represents the physical location of a laboratory.
 * Modeled as an entity within the Laboratory aggregate to allow its own
 * tracking and updates independently, while still belonging to a single Laboratory.</p>
 */
@Getter
public class LaboratoryAddress {

    /**
     * The unique internal numeric identifier for the address entity.
     */
    private Long id;

    /**
     * The full physical address of the laboratory.
     * Mapped to match the single 'address' string from the frontend interfaces.
     */
    private String address;

    /**
     * Default constructor.
     * <p>Required by the persistence and mapping layers (Assemblers) to reconstruct
     * the entity from the database without triggering business logic.</p>
     */
    public LaboratoryAddress() {
        // Required for reconstruction by JPA or Assemblers
    }

    /**
     * Reconstructs a LaboratoryAddress entity from persistence data.
     *
     * @param id The unique numeric ID.
     * @param address The full physical address.
     */
    public LaboratoryAddress(Long id, String address) {
        this.id = id;
        this.address = address;
    }

    /**
     * Constructs a new LaboratoryAddress.
     * <p>The numeric ID is left null to be auto-generated by the persistence mechanism.</p>
     *
     * @param address The full physical address. Cannot be null or blank.
     */
    public LaboratoryAddress(String address) {
        if (address == null || address.isBlank()) {
            throw new IllegalArgumentException("Address cannot be null or blank");
        }
        this.address = address;
    }

    /**
     * Updates the address information.
     * <p>Enforces Fail-Fast validation to ensure the new address is valid.</p>
     *
     * @param newAddress The new physical address. Cannot be null or blank.
     */
    public void update(String newAddress) {
        if (newAddress == null || newAddress.isBlank()) {
            throw new IllegalArgumentException("Address cannot be null or blank");
        }
        this.address = newAddress;
    }
}