package com.iotech.qualitrack.platform.ca.infrastructure.persistence.jpa.repositories;

import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertSeverity;
import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertStatus;
import com.iotech.qualitrack.platform.ca.infrastructure.persistence.jpa.entities.DeviationAlertPersistenceEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA repository for {@link DeviationAlertPersistenceEntity}.
 *
 * <p>Handles database operations for the deviation_alerts table using Long as
 * the primary key. Provides custom queries for filtering alerts by environment,
 * equipment, batch, status, and severity.</p>
 */
@Repository
public interface DeviationAlertPersistenceRepository extends JpaRepository<DeviationAlertPersistenceEntity, Long> {

    /**
     * Finds all alerts generated by a specific equipment.
     *
     * @param equipmentId The numeric ID of the equipment.
     */
    List<DeviationAlertPersistenceEntity> findAllByEquipmentId(Long equipmentId);

    /**
     * Finds all alerts associated with a specific production batch.
     *
     * @param batchId The numeric ID of the batch.
     */
    List<DeviationAlertPersistenceEntity> findAllByBatchId(Long batchId);

    /**
     * Finds all alerts with a specific lifecycle status.
     *
     * @param status The alert lifecycle status.
     */
    List<DeviationAlertPersistenceEntity> findAllByStatus(AlertStatus status);

    /**
     * Finds all alerts with a specific severity level.
     *
     * @param severity The alert severity level.
     */
    List<DeviationAlertPersistenceEntity> findAllBySeverity(AlertSeverity severity);

    /**
     * Finds the alerts of an environment, newest first.
     *
     * @param laboratoryId The numeric ID of the laboratory.
     * @param environmentId The numeric ID of the environment.
     */
    List<DeviationAlertPersistenceEntity> findAllByLaboratoryIdAndEnvironmentIdOrderByIdDesc(Long laboratoryId, Long environmentId);

    /**
     * Finds the latest alert of a device and parameter in one of the given statuses.
     *
     * @param equipmentId The numeric ID of the equipment or IoT device.
     * @param parameterName The monitored parameter.
     * @param statuses The accepted lifecycle statuses.
     */
    Optional<DeviationAlertPersistenceEntity> findFirstByEquipmentIdAndParameterNameAndStatusInOrderByIdDesc(
            Long equipmentId, String parameterName, Collection<AlertStatus> statuses);
}