package com.iotech.qualitrack.platform.ca.infrastructure.persistence.jpa.repositories;

import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertSeverity;
import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertStatus;
import com.iotech.qualitrack.platform.ca.infrastructure.persistence.jpa.entities.DeviationAlertPersistenceEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring Data JPA repository for {@link DeviationAlertPersistenceEntity}.
 *
 * <p>Handles database operations for the deviation_alerts table using Long as
 * the primary key. Provides custom queries for filtering alerts by equipment,
 * batch, status, and severity.</p>
 */
@Repository
public interface DeviationAlertPersistenceRepository extends JpaRepository<DeviationAlertPersistenceEntity, Long> {

    /**
     * Finds all alerts generated by a specific equipment.
     *
     * @param equipmentId The numeric ID of the equipment.
     */
    List<DeviationAlertPersistenceEntity> findAllByEquipmentId(Long equipmentId);

    /**
     * Finds all alerts associated with a specific production batch.
     *
     * @param batchId The numeric ID of the batch.
     */
    List<DeviationAlertPersistenceEntity> findAllByBatchId(Long batchId);

    /**
     * Finds all alerts with a specific lifecycle status.
     *
     * @param status The alert lifecycle status.
     */
    List<DeviationAlertPersistenceEntity> findAllByStatus(AlertStatus status);

    /**
     * Finds all alerts with a specific severity level.
     *
     * @param severity The alert severity level.
     */
    List<DeviationAlertPersistenceEntity> findAllBySeverity(AlertSeverity severity);

    /**
     * Finds all alerts generated by a specific equipment and lifecycle status.
     *
     * @param equipmentId The numeric ID of the equipment.
     * @param status The alert lifecycle status.
     */
    List<DeviationAlertPersistenceEntity> findAllByEquipmentIdAndStatus(Long equipmentId, AlertStatus status);

    /**
     * Finds all alerts associated with a specific batch and lifecycle status.
     *
     * @param batchId The numeric ID of the batch.
     * @param status The alert lifecycle status.
     */
    List<DeviationAlertPersistenceEntity> findAllByBatchIdAndStatus(Long batchId, AlertStatus status);
}