package com.iotech.qualitrack.platform.ra.application.internal.outboundservices.acl;

import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertSeverity;
import com.iotech.qualitrack.platform.ca.domain.model.valueobjects.AlertStatus;
import com.iotech.qualitrack.platform.ca.domain.repositories.DeviationAlertRepository;
import org.springframework.stereotype.Service;

/**
 * ACL service used by the RA bounded context to access compliance alert information.
 *
 * <p>Provides a small anti-corruption boundary over CA data required for KPI
 * calculations, compliance reports, and deviation trend summaries.</p>
 */
@Service
public class RaExternalComplianceService {

    private final DeviationAlertRepository deviationAlertRepository;

    /**
     * Creates the service with the DeviationAlert repository dependency.
     *
     * @param deviationAlertRepository compliance alert repository port
     */
    public RaExternalComplianceService(DeviationAlertRepository deviationAlertRepository) {
        this.deviationAlertRepository = deviationAlertRepository;
    }

    /**
     * Counts all deviation alerts currently registered.
     *
     * @return number of deviation alerts
     */
    public long countAllDeviationAlerts() {
        return deviationAlertRepository.findAll().size();
    }

    /**
     * Counts unresolved deviation alerts.
     *
     * @return number of unresolved deviation alerts
     */
    public long countUnresolvedDeviationAlerts() {
        return deviationAlertRepository.findAllByStatus(AlertStatus.UNRESOLVED).size();
    }

    /**
     * Counts critical deviation alerts.
     *
     * @return number of critical deviation alerts
     */
    public long countCriticalDeviationAlerts() {
        return deviationAlertRepository.findAllBySeverity(AlertSeverity.CRITICAL).size();
    }

    /**
     * Counts deviation alerts generated by a specific equipment.
     *
     * @param equipmentId the equipment identifier
     * @return number of deviation alerts for the equipment
     */
    public long countDeviationAlertsByEquipmentId(Long equipmentId) {
        if (equipmentId == null || equipmentId <= 0) return 0;

        return deviationAlertRepository.findAllByEquipmentId(equipmentId).size();
    }

    /**
     * Counts unresolved deviation alerts generated by a specific equipment.
     *
     * @param equipmentId the equipment identifier
     * @return number of unresolved deviation alerts for the equipment
     */
    public long countUnresolvedDeviationAlertsByEquipmentId(Long equipmentId) {
        if (equipmentId == null || equipmentId <= 0) return 0;

        return deviationAlertRepository
                .findAllByEquipmentIdAndStatus(equipmentId, AlertStatus.UNRESOLVED)
                .size();
    }
}